config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :properties do
    get 'hotels/index'
    get 'hotels/new'
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/pricing', to: 'home#pricing'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


#Admin Routes 
    namespace :admin do
      resources :users
      namespace :guides do
        resources :videos
        resources :texts
      end
      resources :guides
      resources :announcements
      resource :dashboard
      root to: "dashboard#index"
    end


#Guides Routes 
    namespace :guides do
      resources :texts
      resources :videos
    end


  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
    authenticated :user do
      # Add your authenticated route alternates here
      root to: 'properties/hotels#index', as: 'logged_in_root'
      namespace :properties do

        resources :hotels
      end
    end


  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/guides.rb
module Guides
  def self.table_name_prefix
    'guides_'
  end
end

app/models/guides/text.rb
# == Schema Information
#
# Table name: guides_texts
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Guides::Text < ApplicationRecord
  belongs_to :user

  has_rich_text :content
end

app/models/guides/video.rb
# == Schema Information
#
# Table name: guides_videos
#
#  id         :bigint           not null, primary key
#  name       :string
#  video_link :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Guides::Video < ApplicationRecord
  has_rich_text :content
end

app/controllers/admin/guides/texts_controller.rb
class Admin::Guides::TextsController < Admin::GuidesController
  before_action :set_guides_text, only: [:show, :edit, :update, :destroy]

  # GET /guides/texts
  # GET /guides/texts.json
  def index
    @guides_texts = Guides::Text.all
  end

  # GET /guides/texts/1
  # GET /guides/texts/1.json
  def show
  end

  # GET /guides/texts/new
  def new
    @guides_text = Guides::Text.new
  end

  # GET /guides/texts/1/edit
  def edit
  end

  # POST /guides/texts
  # POST /guides/texts.json
  def create
    @guides_text = Guides::Text.new(guides_text_params)
    @guides_text.user = current_user
    @guides_text.published_at = Time.now
    respond_to do |format|
      if @guides_text.save
        format.html { redirect_to @guides_text, notice: 'Text was successfully created.' }
        format.json { render :show, status: :created, location: @guides_text }
      else
        format.html { render :new }
        format.json { render json: @guides_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guides/texts/1
  # PATCH/PUT /guides/texts/1.json
  def update
    respond_to do |format|
      if @guides_text.update(guides_text_params)
        format.html { redirect_to @guides_text, notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @guides_text }
      else
        format.html { render :edit }
        format.json { render json: @guides_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/texts/1
  # DELETE /guides/texts/1.json
  def destroy
    @guides_text.destroy
    respond_to do |format|
      format.html { redirect_to guides_texts_url, notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_guides_text
    @guides_text = Guides::Text.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def guides_text_params
    params.require(:guides_text).permit(:title, :content, :user_id, :published_at)
  end
end

app/controllers/admin/guides/video_controller.rb
class Admin::Guides::VideoController < Admin::GuidesController
end

app/controllers/admin/guides/videos_controller.rb
class Admin::Guides::VideosController < Admin::GuidesController
  before_action :set_guides_text, only: [:show, :edit, :update, :destroy]

  # GET /guides/videos
  # GET /guides/videos.json
  def index
    @guides_videos = Guides::Video.all
  end

  # GET /guides/videos/1
  # GET /guides/videos/1.json
  def show
  end

  # GET /guides/videos/new
  def new
    @guides_video = Guides::Video.new
  end

  # GET /guides/videos/1/edit
  def edit
  end

  # POST /guides/videos
  # POST /guides/videos.json
  def create
    @guides_video = Guides::Video.new(guides_video_params)
    @guides_video.published_at = Time.now
    respond_to do |format|
      if @guides_video.save
        format.html { redirect_to @guides_video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @guides_video }
      else
        format.html { render :new }
        format.json { render json: @guides_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guides/videos/1
  # PATCH/PUT /guides/videos/1.json
  def update
    respond_to do |format|
      if @guides_video.update(guides_video_params)
        format.html { redirect_to @guides_video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @guides_video }
      else
        format.html { render :edit }
        format.json { render json: @guides_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/videos/1
  # DELETE /guides/videos/1.json
  def destroy
    @guides_video.destroy
    respond_to do |format|
      format.html { redirect_to guides_videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_guides_text
    @guides_video = Guides::Video.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def guides_video_params
    params.require(:guides_video).permit(:title, :content, :video_link)
  end


end

app/controllers/admin/guides_controller.rb
class Admin::GuidesController < Admin::BaseController

  def index
    @text_guides = Guides::Text.order(created_at: :desc)
    @video_guides = Guides::Video.order(created_at: :desc)
  end

end

app/controllers/guides/texts_controller.rb
class Guides::TextsController < ApplicationController
  before_action :set_guides_text, only: [:show, :edit, :update, :destroy]

  # GET /guides/texts
  # GET /guides/texts.json
  def index
    @guides_texts = Guides::Text.all
  end

  # GET /guides/texts/1
  # GET /guides/texts/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guides_text
      @guides_text = Guides::Text.find(params[:id])
    end

end

app/controllers/guides/videos_controller.rb
class Guides::VideosController < ApplicationController

  def index
    @videos = Guides::Video.order(created_at: :desc)
  end

end

app/controllers/guides_controller.rb
class Admin::GuidesController < Admin::BaseController

  def index
    # @text_guides = Guides::Text.all
    @video_guides = Guides::Video.order(created_at: :desc)
  end

end

app/views/admin/guides/texts/_form.html.erb
<%= form_for(guides_text, url: admin_guides_texts_url) do |form| %>
  <% if guides_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guides_text.errors.count, "error") %> prohibited this guides_text from being saved:</h2>

      <ul>
        <% guides_text.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-field">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true %>
  </div>

  <div class="form-field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.button "Publish", class: 'btn btn-success', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Publishing..."} %>

    <% if guides_text.persisted? %>
      <%= link_to "Cancel", admin_guides_text_path(guides_text), class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", admin_guides_texts_path, class: "btn btn-link" %>
    <% end %>

    <% if guides_text.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', guides_text, method: :delete, class: "text-danger", data: {confirm: 'Are you sure?'} %>
      </div>
    <% end %>

  </div>
<% end %>

app/views/admin/guides/texts/edit.html.erb
<div class="content">
  <div class="row">
    <div class="col-lg-4 col-md-8 col-sm-12 mx-auto">
      <div class="card card-bordered card-shadow">
        <div class="card-body">
          <h2 class="card-title text-center">Update Guides_text</h2>
          <%= render 'form', guides_text: @guides_text %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/guides/texts/new.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-8 col-sm-12 mx-auto">
      <div class="card card-bordered card-shadow">
        <div class="card-body">
          <h2 class="card-title text-center">New Text Guide</h2>
          <%= render 'form', guides_text: @guides_text %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/guides/texts/show.html.erb
<div class="page-header">
  <%= link_to guides_texts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    All Guides_texts
  <% end %>
  <%= link_to edit_guides_text_path(@guides_text), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show guides_text</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @guides_text.title %></dd>

  <dt>User:</dt>
  <dd><%= @guides_text.user %></dd>

  <dt>Published at:</dt>
  <dd><%= @guides_text.published_at %></dd>

</dl>