config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :properties do
    get 'hotels/index'
    get 'hotels/new'
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/pricing', to: 'home#pricing'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end


#Admin Routes 
    namespace :admin do
      resources :users
      namespace :guides do
        resources :videos
        resources :texts
      end
      resources :guides
      resources :announcements
      resource :dashboard
      root to: "dashboard#index"
    end


#Guides Routes 
    namespace :guides do
      resources :texts
      resources :videos
    end


  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
    authenticated :user do
      # Add your authenticated route alternates here
      root to: 'properties/hotels#index', as: 'logged_in_root'
      namespace :properties do

        resources :hotels
      end
    end


  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer>
  <div class="flex-footer">
    <div class="copyright">
      &copy; <%= Date.today.year %> <%= Rails.configuration.application_name %>
    </div>
    <ul>
      <li>
        <%= link_to 'Terms', terms_path %>
      </li>
      <li>
        <%= link_to 'Privacy', privacy_path %>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %> | <%= yield :title %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<!--Replace this with your preference of fonts-->
<%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav>
  <div class="flex-navbar">
    <%= link_to Rails.configuration.application_name, root_path, class:'navbar-brand' %>
    <button class="mobile-toggle">Menu</button>
    <ul>
      <li>
        <%= link_to "Pricing", pricing_path %>
      </li>
       <li>
        <%= link_to "What's New", announcements_path, class: unread_announcements(current_user) %>
      </li>
      <li>
        <%= link_to "Learn", guides_texts_path %>
      </li>
      <% if current_user.present? %>
        <li>
          <%= link_to '/' do %>
            <span>
              <i aria-hidden="<%= true %>" class="far fa-flag"></i>
            </span>
          <% end %>
        </li>
        <li class="dropdown">
          <%= link_to '#', {data:{toggle:'.dropdown-menu', toggle_class:'active'}} do %>
            <%= image_tag gravatar_image_url(current_user.email, size: 40), height: 20, width: 20 %>
            <span class="username">
              <%= current_user.name %>
            </span>
          <% end %>
          <ul class="dropdown-menu">
            <% if current_user.admin? %>
              <li>
                <%= link_to 'Admin', admin_root_path %>
              </li>
            <% end %>
            <li>
              <%= link_to 'Settings', edit_user_registration_path %>
            </li>
            <li>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <li>
          <%= link_to 'Sign Up', new_user_registration_path %>
        </li>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= yield :secondary_nav %>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>" is="test">
    <div class="container">
      <a class="float-right close" href="#"><span aria-hidden="true">&times;</span></a>
      <%= message %>
    </div>
  </div>
<% end %>